package hoteles.comod.inn.gui.forms;

import hoteles.comod.inn.gui.components.Dialog;
import hoteles.comod.inn.modelos.Cliente;
import hoteles.comod.inn.modelos.Cuenta;
import hoteles.comod.inn.modelos.DetalleCuenta;
import hoteles.comod.inn.modelos.Habitacion;
import hoteles.comod.inn.modelos.Hotel;
import hoteles.comod.inn.modelos.Huesped;
import java.awt.Window;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


public class ReservaForm extends javax.swing.JPanel {

    /**
     * Creates new form ReservaForm
     */
    private Hotel hotel;
    private Habitacion habitacion = null;
    private Cliente cliente = null;

    private final DefaultListModel listaHuespedes;
    private final DefaultComboBoxModel<String> comboBoxClientes;
    private final DefaultComboBoxModel<String> comboBoxHabitaciones;

    
    public ReservaForm(Hotel hotel) {
        initComponents();
        this.hotel = hotel;
        comboBoxClientes = (DefaultComboBoxModel<String>) jComboBox1.getModel();
        comboBoxHabitaciones = (DefaultComboBoxModel<String>) jComboBox2.getModel();
        listaHuespedes = new DefaultListModel();
        jList1.setModel(listaHuespedes);
        cargarClientes();
        cargarHabitaciones();
        ocuparBtn.setEnabled(false);
    }
    
    private void cargarClientes(){
        List<Cliente> clientes = hotel.getServicioCliente().getClientes();
        for(Cliente cliente: clientes){
            comboBoxClientes.addElement(cliente.getNombre());
        }
    }
    
    private void cargarHabitaciones(){
        List<Habitacion> habitaciones = hotel.getServicioHabitacion().getHabitaciones();
        for(Habitacion habitacion: habitaciones){
            if(habitacion.isDisponible()){
                comboBoxHabitaciones.addElement(""+habitacion.getNumeroHabitacion());
                ocuparBtn.setEnabled(true);
            }
        }
    }
    
    private void cargarHuespedes(){
        if(habitacion != null){
            List<Huesped> huespedes = habitacion.getHuespedes();
            listaHuespedes.removeAllElements();
            for(Huesped huesped: huespedes){
                listaHuespedes.addElement(huesped.getNombre());
            }
        }
    }
    
    private void buscarHabitacionSeleccionada(){
        String numeroHabitacion = jComboBox2.getSelectedItem().toString();
         try {
            habitacion = hotel.getServicioHabitacion().buscar(Integer.parseInt(numeroHabitacion));
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ocuparBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(270, 296));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OCUPAR HABITACION");

        jLabel2.setText("Cliente:");

        jLabel3.setText("Fecha Entrada:");

        jLabel4.setText("Fecha Salida:");

        jScrollPane1.setViewportView(jList1);

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Huespedes:");

        ocuparBtn.setText("Ocupar");
        ocuparBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocuparBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Habitacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ocuparBtn)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(ocuparBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ocuparBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocuparBtnActionPerformed
        // TODO add your handling code here:
        Window window = SwingUtilities.getWindowAncestor(ReservaForm.this);
        
        String clienteName = jComboBox1.getSelectedItem().toString();
        try {
            cliente = hotel.getServicioCliente().getClienteByName(clienteName);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        buscarHabitacionSeleccionada();
        
        DetalleCuenta detalleCuenta = new DetalleCuenta("renta habitacion " + habitacion.getTipoHabitacion(), habitacion.getPrecio());
        
        Cuenta cuenta = new Cuenta();
        
        cuenta.registrar(detalleCuenta);
        
        cliente.getServicioCuenta().agregarDetalleCuenta(cuenta);
        
        hotel.getServicioHabitacion().cambiarDisponibilidadHabitacion(habitacion.getNumeroHabitacion(), false);
        window.dispose();
    }//GEN-LAST:event_ocuparBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Huesped huesped = new Huesped();
        
        String numeroHabitacion = jComboBox2.getSelectedItem().toString();
        huesped.setNumeroHabitacion(Integer.parseInt(numeroHabitacion));
        
        Dialog dialog = new Dialog(null, true, new ClienteForm(huesped));
        dialog.setVisible(true);
        
        buscarHabitacionSeleccionada();
        
        habitacion.agregarHuesped(huesped);
        cargarHuespedes();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ocuparBtn;
    // End of variables declaration//GEN-END:variables
}
